[module]
module.name = "Numbers\Documentation\Feedback"
module.code = "F8"
module.title = "F/8 Feedback"
module.version = "1.0.0"

[dependencies]
dep.submodule.Numbers.Backend.Db.__any = 1
dep.submodule.Numbers.Backend.System.Modules = 1
dep.submodule.Numbers.Tenants.Tenants = 1
dep.submodule.Numbers.Users.Organizations = 1
dep.submodule.Numbers.Users.Users = 1
dep.submodule.Numbers.Internalization.Internalization = 1
dep.submodule.Numbers.AI.SDK = 1

; --- models (name and parent class) ---
dep.model.\Numbers\Documentation\Feedback\Model\Types = "\Object\Table"
dep.model.\Numbers\Documentation\Feedback\Model\Feedbacks = "\Object\Table"

; imports
dep.model.\Numbers\Documentation\Feedback\Data\Import = "\Object\Import"
dep.model.\Numbers\Documentation\Feedback\Data\System = "\Object\Import"
dep.model.\Numbers\Documentation\Feedback\Data\Types = "\Object\Import"
; AI
dep.model.\Numbers\Documentation\Feedback\AI\Data\Tools = "\Object\Import"

[help]
; F/8 Feedback
